image: alpine:latest

pages:
  stage: deploy
  script:
    - echo "done"
  artifacts:
    paths:
      - index.html
      - style.css
      - cv.pdf
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
